### ISSUE TITLE
Search is not finding all parameters

### ISSUE THREAD

**Issue by BKLounger** [jmerlan/OpenDefinery-DesktopApp#35]
More feedback on Search. The term "Voltage" brings up zero results! But there are parameters in Collections with this term.
![image](https://user-images.githubusercontent.com/73672905/97640900-fd7ac080-19fe-11eb-8951-af25f080df09.png)

**Comment by jmerlan** [comment]
It turns out this was an issue with the REST API, not the desktop client. I've tested in v0.0.1.3 and it seems to be working now. Please reopen this issue if you're still having issues on your end.
