### ISSUE TITLE
Search results: cannot determine if parameters with identical names also shared GUID's

### ISSUE THREAD

**Issue by BKLounger** [jmerlan/OpenDefinery-DesktopApp#39]
A test search for 'Model" include three results for "Model Number", from three collections. For a user seeking commonality, one wants to know if there are parameter names that may even be common _across_ multiple collections. It would be helpful to know if any identical _**Names**_ also share **_GUID's_**. Some ideas on how to assist a user with this sort of investigation:

1. Show the GUID column in Search results
2. Perhaps have some result filters, things like:
a."Highlight matching GUIDs" or 
b. "Show identical:
[ ] Names  
[ ] GUIDs"

3. Something as simple as making the column headers clickable to sort will help navigate the results

![image](https://user-images.githubusercontent.com/73672905/97762717-a3453280-1ac6-11eb-89e3-b9dbb412b49c.png)

**Comment by jmerlan** [comment]
Added the GUID to the data table so I'm calling this one closed for now. 

I am going to open another ticket as a feature request to improve how search results are displayed. It will be a much bigger refactor of the search results to make them more user-friendly.
